osx_image: xcode8.2
language : objective-c
cache:
  - bundler
  - cocoapods
branche:
  only:
    - develop
    - master
notifications:
  email: false
before_install:
  - gem install bundler
  - bundle install
script:
  - bundle exec fastlane bonjour
